fos_ck_editor:
    configs:
        my_config:
            toolbar: [ [ 'Bold', 'Italic', 'Underline', 'Strike' ] ]
            uiColor:                "#343a40"
            #filebrowserUploadRoute: "my_route"
            #extraPlugins:           "wordcount"