vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true # suppression du fichier à la suppression de l’entité
            delete_on_update: true # suppression du fichier quand un nouveau fichier est envoyé
        art_images:
            uri_prefix: '%app.path.art_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.art_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true # suppression du fichier à la suppression de l’entité
            delete_on_update: true # suppression du fichier quand un nouveau fichier est envoyé
        home_images:
            uri_prefix: '%app.path.home_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.home_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true # suppression du fichier à la suppression de l’entité
            delete_on_update: true # suppression du fichier quand un nouveau fichier est envoyé