vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix:         '%app.path.user_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/users'
        art_images:
            uri_prefix: '%app.path.art_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.art_images%'
        home_images:
            uri_prefix: '%app.path.home_images%'
            upload_destination: '%kernel.root_dir%/../web%app.path.home_images%'